name: Heroku Deployment

on:
  push:
    branches: [ main, heroku-cli-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy with gh-pages
      run: |
        echo "hi"
        heroku git:remote --app ctm-repository
        git push heroku main
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
