name: Heroku Deployment

on:
  push:
    branches: [ main, heroku-cli-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy with heroku
      run: |
        echo "hi"
        git status
        echo "machine git.heroku.com" > ~/.netrc
        echo "  login jrotter@trinity.edu" >> ~/.netrc
        echo ""
        cat ~/.netrc
        heroku git:remote --app ctm-repository
        git push heroku heroku-cli-github-actions
        
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
